runtime: nodejs10 # For Node.js 8, use runtime: nodejs8

instance_class: F2

env_variables:
  BUCKET_NAME: "nextjs-gcloud-bucket"

handlers:
- url: /static
  static_dir: static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto